import { createRequestHandler } from '@opennextjs/cloudflare';

// Create the request handler
const handler = createRequestHandler({
  // Path to the worker file generated by OpenNext
  workerPath: '.open-next/worker.js',
});

// Export the handler for Cloudflare Pages
export default handler;
