name = "practice-energy-app"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Main entry point for the worker - используем OpenNext
main = ".open-next/worker.js"

# Build configuration
[build]
command = "echo 'Build completed by Next.js'"

# Static assets configuration - используем .open-next директорию
[site]
bucket = ".open-next/assets"

# Environment configurations
[env.production]
name = "practice-energy-production"
routes = [
  "app.practice.energy/*",
  "practice.energy/*"
]
# zone_id = "your-zone-id"

[env.staging]
name = "practice-energy-staging"
# routes = [
#   "staging.practice.energy/*"
# ]
# zone_id = "your-zone-id"

[env.preview]
name = "practice-energy-preview"

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"
NEXTJS_SERVER_URL = "https://app.practice.energy"
CUSTOM_KEY = "your-production-custom-key"
BACKEND_URL = "https://api.practice.energy"
NEXT_PUBLIC_API_URL = "https://api.practice.energy"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://api.practice.energy/graphql"

# Environment variables for staging
[env.staging.vars]
NODE_ENV = "staging"
NEXTJS_SERVER_URL = "https://staging.practice.energy"
CUSTOM_KEY = "your-staging-custom-key"
BACKEND_URL = "https://staging-api.practice.energy"
NEXT_PUBLIC_API_URL = "https://staging-api.practice.energy"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://staging-api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://staging-api.practice.energy/graphql"

# Environment variables for preview
[env.preview.vars]
NODE_ENV = "preview"
NEXTJS_SERVER_URL = "https://preview.practice.energy"
CUSTOM_KEY = "your-preview-custom-key"
BACKEND_URL = "https://preview-api.practice.energy"
NEXT_PUBLIC_API_URL = "https://preview-api.practice.energy"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://preview-api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://preview-api.practice.energy/graphql"