name = "webmord"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

# Main entry point for the worker
main = ".open-next/worker.js"

# Build configuration
[build]
command = "npm run build"

# Rules for asset handling - правила с fallback должны идти первыми
[[rules]]
type = "Data"
globs = [".open-next/assets/_next/static/**/*"]

# Специфичные правила для разных типов файлов
[[rules]]
type = "Data"
globs = [".open-next/assets/**/*.css", ".open-next/assets/**/*.scss"]

[[rules]]
type = "Data"
globs = [".open-next/assets/**/*.svg", ".open-next/assets/**/*.png", ".open-next/assets/**/*.jpg", ".open-next/assets/**/*.jpeg", ".open-next/assets/**/*.gif", ".open-next/assets/**/*.ico", "**/*.woff", ".open-next/assets/**/*.woff2", ".open-next/assets/**/*.ttf", ".open-next/assets/**/*.eot"]

[[rules]]
type = "Data"
globs = [".open-next/assets/**/*.bin"]

[[rules]]
type = "ESModule"
globs = [".open-next/assets/**/*.js"]

# Environment configurations
[env.production]
name = "webmord-production"
routes = [
  "app.practice.energy/*",
  "practice.energy/*"
]
zone_id = "your-zone-id"

[env.staging]
name = "webmord-staging"
routes = [
  "staging.practice.energy/*"
]
zone_id = "your-zone-id"

[env.preview]
name = "webmord-preview"

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"
NEXTJS_SERVER_URL = "https://app.practice.energy"
CUSTOM_KEY = "your-production-custom-key"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://api.practice.energy/graphql"

# Environment variables for staging
[env.staging.vars]
NODE_ENV = "staging"
NEXTJS_SERVER_URL = "https://staging.practice.energy"
CUSTOM_KEY = "your-staging-custom-key"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://staging-api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://staging-api.practice.energy/graphql"

# Environment variables for preview
[env.preview.vars]
NODE_ENV = "preview"
NEXTJS_SERVER_URL = "https://preview.practice.energy"
CUSTOM_KEY = "your-preview-custom-key"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://preview-api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://preview-api.practice.energy/graphql"