name = "front-application"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "src/worker.js"

[build]
command = "pnpm run build"
watch_dir = "."

[build.upload]
format = "service-worker"

[env.production]
name = "front-application-production"
route = "app.practice.energy/*"
zone_id = "your-zone-id"

[env.staging]
name = "front-application-staging"
route = "staging.practice.energy/*"
zone_id = "your-zone-id"

[env.preview]
name = "front-application-preview"

[limits]
cpu_ms = 50

# Environment variables
[vars]
NODE_ENV = "production"
NEXTJS_SERVER_URL = "https://app.practice.energy"
CUSTOM_KEY = "your-custom-key"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://api.practice.energy/graphql"

[env.production.vars]
NODE_ENV = "production"
CUSTOM_KEY = "your-production-custom-key"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://api.practice.energy/graphql"

[env.staging.vars]
NODE_ENV = "staging"
CUSTOM_KEY = "your-staging-custom-key"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://staging-api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://staging-api.practice.energy/graphql"

[env.preview.vars]
NODE_ENV = "preview"
CUSTOM_KEY = "your-preview-custom-key"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://preview-api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://preview-api.practice.energy/graphql"
