name = "front-application"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "CACHE"
id = "your-cache-kv-namespace-id"
preview_id = "your-cache-kv-namespace-preview-id"

[[kv_namespaces]]
binding = "SESSIONS"
id = "your-sessions-kv-namespace-id"
preview_id = "your-sessions-kv-namespace-preview-id"

[[d1_databases]]
binding = "DB"
database_name = "practice-db"
database_id = "your-d1-database-id"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "practice-uploads"

[build]
command = "pnpm run build"
watch_dir = "."

[build.upload]
format = "service-worker"

[env.production]
name = "front-application-production"
route = "practice.energy/*"
zone_id = "your-zone-id"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your-prod-cache-kv-namespace-id"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "your-prod-sessions-kv-namespace-id"

[[env.production.d1_databases]]
binding = "DB"
database_name = "practice-db-prod"
database_id = "your-prod-d1-database-id"

[[env.production.r2_buckets]]
binding = "UPLOADS"
bucket_name = "practice-uploads-prod"

[env.staging]
name = "front-application-staging"
route = "staging.practice.energy/*"
zone_id = "your-zone-id"

[env.preview]
name = "front-application-preview"

# Environment variables
[vars]
NODE_ENV = "production"
CUSTOM_KEY = "your-custom-key"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://api.practice.energy/graphql"

[env.production.vars]
NODE_ENV = "production"
CUSTOM_KEY = "your-production-custom-key"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://api.practice.energy/graphql"

[env.staging.vars]
NODE_ENV = "staging"
CUSTOM_KEY = "your-staging-custom-key"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://staging-api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://staging-api.practice.energy/graphql"

[env.preview.vars]
NODE_ENV = "preview"
CUSTOM_KEY = "your-preview-custom-key"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://preview-api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://preview-api.practice.energy/graphql"
