name = "webmord"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

# Main entry point for the worker
main = ".open-next/worker.js"

# Build configuration
[build]
command = "npm run build"

# OpenNext автоматически обрабатывает все файлы, правила не нужны

# Environment configurations
[env.production]
name = "webmord"
routes = [
  "app.practice.energy/*",
  "practice.energy/*"
]
zone_id = "your-zone-id"

[env.staging]
routes = [
  "staging.practice.energy/*"
]
zone_id = "your-zone-id"

[env.preview]

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"
NEXTJS_SERVER_URL = "https://app.practice.energy"
CUSTOM_KEY = "your-production-custom-key"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://api.practice.energy/graphql"

# Environment variables for staging
[env.staging.vars]
NODE_ENV = "staging"
NEXTJS_SERVER_URL = "https://staging.practice.energy"
CUSTOM_KEY = "your-staging-custom-key"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://staging-api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://staging-api.practice.energy/graphql"

# Environment variables for preview
[env.preview.vars]
NODE_ENV = "preview"
NEXTJS_SERVER_URL = "https://preview.practice.energy"
CUSTOM_KEY = "your-preview-custom-key"
NEXT_PUBLIC_GRAPHQL_HTTP_URL = "https://preview-api.practice.energy/graphql"
NEXT_PUBLIC_GRAPHQL_WS_URL = "wss://preview-api.practice.energy/graphql"