import type { Booking } from "@/types/booking"

export const mockBookings: Booking[] = [
  {
    id: "1",
    clientId: "client-1",
    specialistId: "specialist-1",
    serviceId: "service-1",
    date: new Date(2025, 0, 15, 5, 0), // January 15, 2025, 05:00
    duration: 60,
    status: "confirmed",
    format: "video",
    paymentStatus: "paid",
    totalAmount: 3000,
    notes: "Таро расклад на судьбу",
    service: {
      id: "service-1",
      name: "Таро расклад на судьбу",
      description: "Подробный расклад на судьбу",
      price: 3000,
      duration: 60,
      category: "Таро",
    },
    specialist: {
      id: "specialist-1",
      name: "Афалина",
      photo: "/placeholder-user.jpg",
      rating: 4.9,
      reviewsCount: 127,
    },
    client: {
      id: "client-1",
      name: "Иван Петров",
      photo: "/placeholder-user.jpg",
    },
  },
  {
    id: "2",
    clientId: "client-2",
    specialistId: "specialist-2",
    serviceId: "service-2",
    date: new Date(2025, 0, 15, 6, 0), // January 15, 2025, 06:00
    duration: 90,
    status: "upcoming",
    format: "offline",
    paymentStatus: "pending",
    totalAmount: 4500,
    notes: "Таро расклад на судьбу",
    service: {
      id: "service-2",
      name: "Таро расклад на судьбу",
      description: "Расклад на судьбу и карьеру",
      price: 4500,
      duration: 90,
      category: "Таро",
    },
    specialist: {
      id: "specialist-2",
      name: "Мария Иванова",
      photo: "/placeholder-user.jpg",
      rating: 4.8,
      reviewsCount: 89,
    },
    client: {
      id: "client-2",
      name: "Анна Сидорова",
      photo: "/placeholder-user.jpg",
    },
  },
  {
    id: "3",
    clientId: "client-3",
    specialistId: "specialist-3",
    serviceId: "service-3",
    date: new Date(2025, 0, 15, 17, 0), // January 15, 2025, 17:00
    duration: 120,
    status: "upcoming",
    format: "video",
    paymentStatus: "pending",
    totalAmount: 5000,
    notes: "Разбор натальной карты для женщин",
    service: {
      id: "service-3",
      name: "Разбор натальной карты для женщин",
      description: "Полный разбор натальной карты",
      price: 5000,
      duration: 120,
      category: "Астрология",
    },
    specialist: {
      id: "specialist-3",
      name: "Снежана",
      photo: "/placeholder-user.jpg",
      rating: 4.7,
      reviewsCount: 156,
    },
    client: {
      id: "client-3",
      name: "Елена Козлова",
      photo: "/placeholder-user.jpg",
    },
  },
]
