import type { Booking } from "@/types/booking"

export const mockBookings: Booking[] = [
  {
    id: "1",
    service: {
      id: "s1",
      name: "Таро расклад на судьбу",
      description: "Подробный расклад на судьбу",
      price: 3000,
      duration: 60,
      category: "Таро",
    },
    specialist: {
      id: "sp1",
      name: "Афалина",
      photo: "/placeholder-user.jpg",
      rating: 4.8,
      reviewsCount: 124,
      specialties: ["Таро", "Астрология"],
    },
    date: new Date().toISOString(),
    duration: 60,
    slots: 1,
    format: "video",
    status: "confirmed",
    paymentStatus: "paid",
    clientId: "c1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    service: {
      id: "s2",
      name: "Разбор натальной карты детально",
      description: "Полный разбор натальной карты",
      price: 5000,
      duration: 120,
      category: "Астрология",
    },
    specialist: {
      id: "sp2",
      name: "Снежана",
      photo: "/placeholder-user.jpg",
      rating: 4.9,
      reviewsCount: 89,
      specialties: ["Астрология", "Нумерология"],
    },
    date: new Date(new Date().setHours(17, 0, 0, 0)).toISOString(),
    duration: 120,
    slots: 2,
    format: "in-person",
    status: "upcoming",
    paymentStatus: "pending",
    clientId: "c2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    service: {
      id: "s3",
      name: "Консультация по отношениям",
      description: "Работа с отношениями",
      price: 4000,
      duration: 90,
      category: "Психология",
    },
    specialist: {
      id: "sp3",
      name: "Елена",
      photo: "/placeholder-user.jpg",
      rating: 4.7,
      reviewsCount: 156,
      specialties: ["Психология", "Коучинг"],
    },
    date: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(),
    duration: 90,
    slots: 2,
    format: "video",
    status: "confirmed",
    paymentStatus: "paid",
    clientId: "c3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
