// Mock данные для услуг (обновлены ID)
import {mockSpecialists} from "@/services/mock-specialists";
import {mockFeedbacks} from "@/services/mock-feedbacks";
import {v4 as uuidv4} from "uuid";
import {service1Id, service2Id, specialist1Id, specialist2Id} from "@/services/mock-data";
import {Service} from "@/types/service";

export const mockServices: Service[] = [
    {
        id: service1Id,
        title: "Натальная карта",
        description: "Подробный разбор натальной карты с рекомендациями",
        priceInPerson: 3500,
        priceVideo: 300,
        durationVideo: 300,
        durationInPerson: 300,
        images: [
            "/placeholder.jpg",
            "/placeholder.jpg",
        ],
        contents: "Подробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациями",
        specialist: mockSpecialists[0],
        tags: ["астрология", "натальная карта", "личность"],
        reviews: mockFeedbacks,
        includes: ["Wipes", "Pencils", "Markers", "Wipes", "Pencils", "Markers"],
        format: ["video", "in-person"],
        practiceInPerson: 30,
        practiceVideo: 30,
        location: "Бибирево, Большая Ленина",
        bookings: [
            {
                id: uuidv4(),
                startTime: new Date(),
                endTime: new Date(),
                status: "confirmed",
                createdAt: new Date(),
                updatedAt: new Date(),
                isRepeat: false,
                duration: 30,
                format: "video"
            },
            {
                id: uuidv4(),
                startTime: new Date(),
                endTime: new Date(),
                status: "confirmed",
                createdAt: new Date(),
                updatedAt: new Date(),
                isRepeat: false,
                duration: 240,
                format: "in-person"
            },
        ]
    },
    {
        id: service2Id,
        title: "Коучинг сессия",
        description: "Индивидуальная коучинг сессия для достижения целей",
        priceInPerson: 3500,
        priceVideo: 300,
        contents: "Подробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациями",
        duration: "90 минут",
        images: ["/placeholder.jpg"],
        specialist: mockSpecialists[0],
        tags: ["коучинг", "цели", "развитие"],
        reviews: mockFeedbacks,
        includes: ["Wipes", "Pencils", "Markers"],
        format: ["video"],
        practice: "30 минут",
    },
    {
        id: uuidv4(),
        title: "Натальная карта",
        description: "Полный анализ натальной карты с разбором основных аспектов и домов",
        contents: "Подробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациями",
        priceInPerson: 3500,
        priceVideo: 300,
        duration: "1.5 часа",
        images: ["/astrology-service1.jpg", "/astrology-service2.jpg"],
        includes: [
            "Подробный разбор планет в знаках",
            "Анализ аспектов",
            "Рекомендации по развитию",
            "Запись консультации",
        ],
        specialist: {
            id: specialist1Id,
            name: "Анна Петрова",
            title: "Астролог и таролог",
            avatar: "placeholder.svg"
        },
        tags: ["натальная карта", "астрология", "индивидуальная консультация"],
        reviews: [],
        format: ["video", "in-person"],
        practice: "30 минут",
    },
    {
        id: uuidv4(),
        title: "Гадание на Таро",
        description: "Ответы на вопросы с помощью карт Таро с детальным толкованием",
        priceInPerson: 3500,
        priceVideo: 300,
        duration: "1 час",
        contents: "Подробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациями",
        images: ["/taro-service1.jpg"],
        includes: ["Ответы на 3 ключевых вопроса", "Разбор текущей ситуации", "Рекомендации на ближайший месяц"],
        specialist: {
            id: specialist1Id,
            name: "Анна Петрова",
            title: "Астролог и таролог",
            avatar: "placeholder.svg"
        },
        tags: ["таро", "гадание", "предсказание"],
        reviews: [],
        format: ["video", "in-person"],
        practice: "30 минут",
    },
    {
        id: uuidv4(),
        title: "Карьерный коучинг",
        description: "Индивидуальная сессия по поиску профессионального пути",
        priceInPerson: 3500,
        priceVideo: 300,
        contents: "Подробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациями",
        duration: "1.5 часа",
        images: ["/coaching-service1.jpg", "/coaching-service2.jpg"],
        includes: [
            "Анализ текущей ситуации",
            "Определение сильных сторон",
            "Разработка плана развития",
            "Дополнительные материалы",
        ],
        specialist: {
            id: specialist2Id,
            name: "Михаил Сидоров",
            title: "Лайф-коуч и бизнес-тренер",
            avatar: "placeholder.svg"
        },
        tags: ["карьера", "коучинг", "профессиональное развитие"],
        reviews: [],
        format: ["video", "in-person"],
        practice: "30 минут",
    },
    {
        id: uuidv4(),
        title: "Пакет из 5 коуч-сессий",
        description: "Комплексная работа над достижением целей с сопровождением",
        priceInPerson: 3500,
        priceVideo: 300,
        contents: "Подробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациямиПодробный разбор натальной карты с рекомендациями",
        duration: "5 сессий по 1 часу",
        images: ["/coaching-package.jpg"],
        includes: ["Первичная диагностика", "5 индивидуальных сессий", "Промежуточные задания", "Поддержка между сессиями"],
        specialist: {
            id: specialist2Id,
            name: "Михаил Сидоров",
            title: "Лайф-коуч и бизнес-тренер",
            avatar: "placeholder.svg"
        },
        tags: ["пакет", "коучинг", "личное развитие"],
        reviews: [],
        format: ["video", "in-person"],
        practice: "30 минут",
    },
]
