name: Quick Deploy

on:
  push:
    branches: [main, master, dev, prod]
    paths-ignore:
      - '**.md'
      - '.github/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
        - preview

env:
  NODE_VERSION: '18'
  PNPM_VERSION: '8'

jobs:
  quick-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build project
        run: pnpm run build
        env:
          NEXT_PUBLIC_GRAPHQL_HTTP_URL: ${{ secrets.NEXT_PUBLIC_GRAPHQL_HTTP_URL }}
          NEXT_PUBLIC_GRAPHQL_WS_URL: ${{ secrets.NEXT_PUBLIC_GRAPHQL_WS_URL }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: quick-build-output
          path: .next/
          retention-days: 1
          
  quick-deploy-production:
    runs-on: ubuntu-latest
    needs: quick-build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/prod' || github.event.inputs.environment == 'production'
    
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: quick-build-output
          path: .next/
          
      - name: Deploy to Cloudflare Pages (Production)
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: .next
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          
  quick-deploy-staging:
    runs-on: ubuntu-latest
    needs: quick-build
    if: github.ref == 'refs/heads/dev' || github.event.inputs.environment == 'staging'
    
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: quick-build-output
          path: .next/
          
      - name: Deploy to Cloudflare Pages (Staging)
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: .next
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
